### ISSUE TITLE
RSS question

### ISSUE THREAD

**Issue by sentensos** [csrutil/realtek-r8125-openwrt#5]
Hi! Thank you for releasing drivers with RSS for openwrt!
i can't get the documentation, you set 2 cores for intel i211 2 queues for 2 nic's

For example i have x2 i210 nic's with 4 queues and 2 core 4 thread cpu, should i put RSS=4,8? or 2,4? RSS=x,y?

**Comment by OpenNya** [comment]
Hi! 
I am not related with this code repository in any manner, but according documentation (README file from intel igb driver package):

`igb [<option>=<VAL1>,<VAL2>,...]`
```
A value (<VAL#>) must be assigned to each network port in the system supported by this driver. 
The values are applied to each instance, in function order.
```
In the case of two network ports installed in the system having 2-Core CPU the command syntax would be:

`igb RSS=2,2`

A note regarding HyperThreaded (HT) CPU cores.
In your particular case (2-Core/4-Thread CPU) It is recommended no more than 2 queues per port because for the driver hyper-threads typically add little to no additional performance gain since they are not true cores and they take away from work being done on other CPUs.

WBR

**Comment by csrutil** [comment]
I'm closing this issue, thank you!
